name: Docker UltraGroupHotels
on:
  push:
    branches: ["master"]

jobs:
  deploy:
    name: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3 
      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Web API image
        run: |
          docker build --platform linux --tag rogerroldan/ultragrouphotels:latest -f src/UltraGroupHotels.WebAPI/Dockerfile .

      - name: Publish Web API image
        run: |
          docker push rogerroldan/ultragrouphotels:latest

      - name: Service Auth Azure
        uses: azure/webapps-deploy@v3.0.1
        with:
          app-name: 'ultragrouphotels'
          publish-profile: ${{ secrets.AZURE_PUBLISH_SUSCRIPTION_APP_SERVICES }}
          images: 'rogerroldan/ultragrouphotels:latest'
    